// Code generated by wit-bindgen-go. DO NOT EDIT.

package adder

// This file contains wasmimport and wasmexport declarations for "docs:adder@0.1.0".

//go:wasmexport add
//export add
func wasmexport_Add(x0 uint32, y0 uint32) (result0 uint32) {
	x := (int32)((uint32)(x0))
	y := (int32)((uint32)(y0))
	result := Exports.Add(x, y)
	result0 = (uint32)(result)
	return
}
